# dbt project name
name: 'enterprise_survey_transform'
version: '1.0.0'
config-version: 2

# the link to the profiles.yml
profile: 'enterprise_survey_elt_pipeline'

# default folders dbt will look in for different file types
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory for compiled files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# This section allows you to apply configurations to your models.
models:
  # configurations for the 'enterprise_survey_transform' project
  enterprise_survey_transform:
    # configurations for all models inside the 'models/staging' directory
    staging:
      # tells dbt to create these models as VIEWS in the database.
      materialized: view
    # Configurations for all models inside the 'models/marts' directory
    marts:
      # This tells dbt to create these models as TABLES in the database.
      # Tables store data physically and are faster to query.
      materialized: table